production:
  url: <%= ENV['DATABASE_URL'] %>
  
development:
  adapter: postgresql
  database: kelly_anagrams_development
  pool: 5
  host: localhost
  username: CCM
  password: nico

test:
  adapter: postgresql
  database: kelly_anagrams_test
  pool: 5
  host: localhost
  username: CCM
  password: nico